---
- name: My Test Playbook
  hosts: webservers
  become: true
  tasks:
  - name: stop httpd service
    service:
      name: httpd
      state: stopped

  - name: Uninstalled httpd package
    yum:
      name: httpd
      state: removed
